language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

#script which has to be executed
script:
  -docker run -e CI=true react-test npm test

#after the build what has to be done
after_success:
  - docker build -t multi-client ./client
  - docker build -t multi-nginx ./nginx
  - docker build -t multi-server ./server
  - docker build -t multi-worker ./worker
#take images push to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#taking images and pushing into docker hub
  - docker push multi-client
  - docker push multi-nginx
  - docker push multi-server
  - docker push multi-worker